
base:
  log_level: INFO
  random_state: 42

get_dataset:
  inseason_dataset: ./data/input/nba_games_inseason_dataset_final.csv
  training_dataset: ./data/input/nba_games_training_dataset_final.csv

get_models:
  model: ./models/model.joblib
  model_columns: ./models/columns_selected.csv

inference:
  target_variable: results
  group_cv_variable: id
  dataset: ./data/output/nba_games_inseasonn_w_pred.csv
